#!/bin/bash

set -e

echo "Building CV32E40P testbench..."

DEFAULT_VERILATOR_INSTALL_DIR=$(pwd)/install/verilator
VERILATOR_INSTALL_DIR=${VERILATOR_INSTALL_DIR:-$DEFAULT_VERILATOR_INSTALL_DIR}

export PATH=$VERILATOR_INSTALL_DIR/bin:$PATH

COREVVERIF_DIR=$(pwd)/core-v-verif
CV32E40P_DIR=$(pwd)/cv32e40p

make -C $COREVVERIF_DIR/cv32e40p/sim/core CV_SW_TOOLCHAIN=_ CV_SW_PREFIX=_ CV_CORE_PATH=$CV32E40P_DIR VERBOSE=1 clean
make -C $COREVVERIF_DIR/cv32e40p/sim/core CV_SW_TOOLCHAIN=_ CV_SW_PREFIX=_ CV_CORE_PATH=$CV32E40P_DIR CV_CORE_PKG=$CV32E40P_DIR VERBOSE=1 LOG_INSNS=1 WAVES=0 testbench_verilator
